[package]
name = "rustgit"
version = "1.1.0"
authors = ["Dan Farino <dan.farino@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.14.4"
regex = "1.6.0"
chrono = "0.4.19"
clap = "3.2.14"
anyhow = "1.0.58"
atty = "0.2.14"
glob = "0.3.0"
dirs = "4.0.0"
shellexpand = "2.1.0"
openssl-sys = "0.9.75"
openssl = "0.10.41"
