[package]
name = "rustgit"
version = "0.1.0"
authors = ["Dan Farino <dan.farino@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.24"
regex = "1.5.4"
chrono = "0.4.19"
clap = "3.0.0-beta.5"
anyhow = "1.0.49"
atty = "0.2.14"
glob = "0.3.0"
dirs = "4.0.0"
shellexpand = "2.1.0"
